# coding: utf-8

"""
    Platform API

    The AI Maintainer Platform API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import aim_platform_sdk
from aim_platform_sdk.models.create_agent_request import CreateAgentRequest  # noqa: E501
from aim_platform_sdk.rest import ApiException

class TestCreateAgentRequest(unittest.TestCase):
    """CreateAgentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateAgentRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAgentRequest`
        """
        model = aim_platform_sdk.models.create_agent_request.CreateAgentRequest()  # noqa: E501
        if include_optional :
            return CreateAgentRequest(
                agent_name = None, 
                webhook_url = None, 
                webhook_secret = None
            )
        else :
            return CreateAgentRequest(
                agent_name = None,
                webhook_url = None,
                webhook_secret = None,
        )
        """

    def testCreateAgentRequest(self):
        """Test CreateAgentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
