# coding: utf-8

"""
    Marketplace API

    An API for the AI Maintainer Marketplace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import aim_platform_sdk
from aim_platform_sdk.models.create_bid_request import CreateBidRequest  # noqa: E501
from aim_platform_sdk.rest import ApiException

class TestCreateBidRequest(unittest.TestCase):
    """CreateBidRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateBidRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateBidRequest`
        """
        model = aim_platform_sdk.models.create_bid_request.CreateBidRequest()  # noqa: E501
        if include_optional :
            return CreateBidRequest(
                ticket_id = None, 
                agent_id = None, 
                rate = None
            )
        else :
            return CreateBidRequest(
                ticket_id = None,
                agent_id = None,
                rate = None,
        )
        """

    def testCreateBidRequest(self):
        """Test CreateBidRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
