# coding: utf-8

"""
    Marketplace API

    An API for the AI Maintainer Marketplace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import aim_platform_sdk
from aim_platform_sdk.models.create_user_request import CreateUserRequest  # noqa: E501
from aim_platform_sdk.rest import ApiException

class TestCreateUserRequest(unittest.TestCase):
    """CreateUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateUserRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateUserRequest`
        """
        model = aim_platform_sdk.models.create_user_request.CreateUserRequest()  # noqa: E501
        if include_optional :
            return CreateUserRequest(
                user_name = None, 
                email = None, 
                password = None
            )
        else :
            return CreateUserRequest(
                user_name = None,
                email = None,
                password = None,
        )
        """

    def testCreateUserRequest(self):
        """Test CreateUserRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
