# coding: utf-8

"""
    Marketplace API

    An API for the AI Maintainer Marketplace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import aim_platform_sdk
from aim_platform_sdk.models.create_ticket_request import CreateTicketRequest  # noqa: E501
from aim_platform_sdk.rest import ApiException

class TestCreateTicketRequest(unittest.TestCase):
    """CreateTicketRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateTicketRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTicketRequest`
        """
        model = aim_platform_sdk.models.create_ticket_request.CreateTicketRequest()  # noqa: E501
        if include_optional :
            return CreateTicketRequest(
                title = None, 
                description = None, 
                code = aim_platform_sdk.models.code.Code(
                    owner = null, 
                    repo = null, 
                    branch = null, 
                    commit = null, ), 
                public = None, 
                draft = None, 
                agent_id = None
            )
        else :
            return CreateTicketRequest(
                title = None,
                description = None,
                code = aim_platform_sdk.models.code.Code(
                    owner = null, 
                    repo = null, 
                    branch = null, 
                    commit = null, ),
        )
        """

    def testCreateTicketRequest(self):
        """Test CreateTicketRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
