# coding: utf-8

"""
    Marketplace API

    An API for the AI Maintainer Marketplace

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import aim_platform_sdk
from aim_platform_sdk.models.agent import Agent  # noqa: E501
from aim_platform_sdk.rest import ApiException

class TestAgent(unittest.TestCase):
    """Agent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Agent
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Agent`
        """
        model = aim_platform_sdk.models.agent.Agent()  # noqa: E501
        if include_optional :
            return Agent(
                agent_id = None, 
                agent_name = None, 
                user_id = None, 
                user_name = None, 
                webhook_url = None, 
                webhook_secret = None, 
                created_at = None, 
                updated_at = None
            )
        else :
            return Agent(
                agent_id = None,
                agent_name = None,
                user_id = None,
                user_name = None,
                webhook_url = None,
                webhook_secret = None,
                created_at = None,
                updated_at = None,
        )
        """

    def testAgent(self):
        """Test Agent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
