# coding: utf-8

"""
    Marketplace API

    An API for the AI Maintainer Marketplace  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import aim_platform_sdk
from aim_platform_sdk.model.user_response import UserResponse
from aim_platform_sdk import configuration


class TestUserResponse(unittest.TestCase):
    """UserResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
