# coding: utf-8

"""
    Platform API

    The AI Maintainer Platform API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Optional
from pydantic import BaseModel, Field

class UpdateRepositoryRequest(BaseModel):
    """
    UpdateRepositoryRequest
    """
    repository_name: Optional[Any] = Field(..., alias="repositoryName", description="The unique name of the repository.")
    is_public: Optional[Any] = Field(..., alias="isPublic", description="Whether the repository is public.")
    __properties = ["repositoryName", "isPublic"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UpdateRepositoryRequest:
        """Create an instance of UpdateRepositoryRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if repository_name (nullable) is None
        # and __fields_set__ contains the field
        if self.repository_name is None and "repository_name" in self.__fields_set__:
            _dict['repositoryName'] = None

        # set to None if is_public (nullable) is None
        # and __fields_set__ contains the field
        if self.is_public is None and "is_public" in self.__fields_set__:
            _dict['isPublic'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UpdateRepositoryRequest:
        """Create an instance of UpdateRepositoryRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UpdateRepositoryRequest.parse_obj(obj)

        _obj = UpdateRepositoryRequest.parse_obj({
            "repository_name": obj.get("repositoryName"),
            "is_public": obj.get("isPublic")
        })
        return _obj


