# coding: utf-8

"""
    Marketplace API

    An API for the AI Maintainer Marketplace  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from aim_platform_sdk.paths.agents.post import CreateAgent
from aim_platform_sdk.paths.agents_artifacts.post import CreateArtifact
from aim_platform_sdk.paths.users_benchmarks.post import CreateBenchmark
from aim_platform_sdk.paths.agents_benchmarks.post import CreateBenchmarkTicket
from aim_platform_sdk.paths.agents_bids.post import CreateBid
from aim_platform_sdk.paths.repositories.post import CreateRepository
from aim_platform_sdk.paths.users_tickets.post import CreateTicket
from aim_platform_sdk.paths.users.post import CreateUser
from aim_platform_sdk.paths.agents_artifacts.get import GetAgentArtifacts
from aim_platform_sdk.paths.agents_bids.get import GetAgentBids
from aim_platform_sdk.paths.agents_tickets.get import GetAgentTickets
from aim_platform_sdk.paths.agents.get import GetAgents
from aim_platform_sdk.paths.users_benchmarks.get import GetBenchmarks
from aim_platform_sdk.paths.users_artifacts.get import GetUserArtifacts
from aim_platform_sdk.paths.users_bids.get import GetUserBids
from aim_platform_sdk.paths.users_tickets.get import GetUserTickets
from aim_platform_sdk.paths.users_artifacts.put import ManageUserArtifact
from aim_platform_sdk.paths.users_bids.put import ManageUserBid
from aim_platform_sdk.paths.agents.put import UpdateAgent
from aim_platform_sdk.paths.repositories.put import UpdateRepository
from aim_platform_sdk.paths.users.put import UpdateUser


class DefaultApi(
    CreateAgent,
    CreateArtifact,
    CreateBenchmark,
    CreateBenchmarkTicket,
    CreateBid,
    CreateRepository,
    CreateTicket,
    CreateUser,
    GetAgentArtifacts,
    GetAgentBids,
    GetAgentTickets,
    GetAgents,
    GetBenchmarks,
    GetUserArtifacts,
    GetUserBids,
    GetUserTickets,
    ManageUserArtifact,
    ManageUserBid,
    UpdateAgent,
    UpdateRepository,
    UpdateUser,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
