# coding: utf-8

"""
    Marketplace API

    An API for the AI Maintainer Marketplace  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.agents.post import CreateAgent
from openapi_client.paths.agents_artifacts.post import CreateArtifact
from openapi_client.paths.agents_bids.post import CreateBid
from openapi_client.paths.users.post import CreateUser
from openapi_client.paths.agents_artifacts.get import GetAgentArtifacts
from openapi_client.paths.agents_bids.get import GetAgentBids
from openapi_client.paths.agents_tickets.get import GetAgentTickets
from openapi_client.paths.agents.get import GetAgents
from openapi_client.paths.users_tickets.get import GetUserTickets
from openapi_client.paths.users.put import UpdatePassword
from openapi_client.paths.agents.put import UpdateUser


class DefaultApi(
    CreateAgent,
    CreateArtifact,
    CreateBid,
    CreateUser,
    GetAgentArtifacts,
    GetAgentBids,
    GetAgentTickets,
    GetAgents,
    GetUserTickets,
    UpdatePassword,
    UpdateUser,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
